server:
  port: 9292
  servlet:
    context-path: '@app.context-path@'

spring:
  main:
    banner-mode: 'off'
  profiles:
    active: '@activatedProperties@'
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:mysql://localhost:3306/disney?useSSL=false&useFractionalSeconds=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 604800000



---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: prod




